### ISSUE TITLE
Why bother returning a Result when you only ever return Ok?

### ISSUE THREAD

**Issue by jgall** [unixpickle/myodine#18]
https://github.com/unixpickle/myodine/blob/db19e9a33224de8baac911d239ac58aa4966ca1d/src/server/flags.rs#L62

**Comment by unixpickle** [comment]
There's a bunch of places the function returns an error. Every time there is an expression `foo?`, that compiles to something like:

```
if let Err(e) = foo {
     return Err(e);
} else {
     ...
}
```

The `?` operator is so slick that it's to miss all the implicit Err returns :)
